name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install flake8
      - run: flake8 --ignore=E501,F401,E722 tests xtarfile

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: [3.5, 3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install -e .[lz4,zstd,pytest]
      - run: pytest
